name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Run the build
      run: docker run --entrypoint 'sh' --rm -v `pwd`:/app mcostea/pi-photo-frame-builder cargo build -j 1 --release && cargo deb -v

    - name: Create package
      run: tar -czvf pi-photo-builder.tar.gz target/debian/*

    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: pi-photo-frame
        path: pi-photo-builder.tar.gz
