name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install qemu-user-static
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t pi-photo-builder --platform linux/arm64 .

    - name: Run the build
      run: docker run --rm -v `pwd`:/app --platform linux/arm64 pi-photo-builder

    - name: Create package
      run: tar -czvf pi-photo-builder.tar.gz target/debian/*

    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: pi-photo-frame
        path: pi-photo-builder.tar.gz
