name: Release app

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set the Sentry DSN
        run: sed -i "s/SENTRY_DSN/${{ secrets.SENTRY_DSN }}/g" src/main.rs

      - name: Run the build
        run: docker run --rm -v `pwd`:/builder mcostea/pi-photo-frame-builder

      - name: Create package
        run: tar -czvf pi-photo-builder.tar.gz target/aarch64-unknown-linux-gnu/debian/*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "pi-photo-builder.tar.gz"
